# Generated by Django 5.0.6 on 2024-06-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_comment_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='car',
        ),
    ]
