# Generated by Django 5.0.6 on 2024-06-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_comment_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
