# Generated by Django 5.0.6 on 2024-06-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='quantity',
            field=models.IntegerField(max_length=255),
        ),
    ]
